#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define MAX_ABILITIES 2
#define MAX_AVAILABLE_ABILITIES 3
#define PUNCH 0
#define HEAL 1
#define RISKY_PUNCH 2

#define PUNCH_DAMAGE 1
#define HEAL_VALUE 1
#define RISKY_PUNCH_VALUE 2
#define MAX_PREMADE_CHARACTERS 2
#define MAX_CHOSEN_CHARACTERS 2

#define LOWEST_INPUT_OPTION 0
#define HIGHEST_INPUT_OPTION 1
#define INPUT_ZERO 0
#define INPUT_ONE 1
#define INPUT_TWO 2

#define CHOOSING_CHARACTER_LOWEST_INPUT_OPTION 0
#define CHOOSING_CHARACTER_HIGHEST_INPUT_OPTION 2

#define ROUND_TO_CHOOSE_YOUR_CHARACTER 1
#define ROUND_TO_CHOOSE_COMPUTER_CHARACTER 2
#define CHOOSING_OVER 3

#define YOUR_CHARACTER_INDEX 0
#define COMPUTER_CHARACTER_INDEX 1

#define PLAYER 0
#define COMPUTER 1

#endif // CONFIG_H_INCLUDED
